#!/usr/bin/groovy

// Copyright (C) Luxoft Sweden AB 2018

void buildBistro(String variant, String imageName) {
    String bistroDir = "meta-bistro"
    node("Yocto") {
        dir(bistroDir) {
            checkout scm
        }

        // Initialize pelux-manifests to get the code
        sh "rm -rf pelux-manifests/"
        sh "git clone https://github.com/Pelagicore/pelux-manifests.git"

        dir('pelux-manifests') {
            def code = load "ci-scripts/yocto.groovy"
            String bistroPath = "${env.WORKSPACE}/${bistroDir}"
            code.buildWithLayer(variant, imageName, bistroDir, bistroPath)
        }
    }
}

def variantMap = [:]
def variantList = env.VARIANT_LIST.split()

variantList.each {
    def list = it.split(":")
    variantMap["${list[0]}"] = {
        buildBistro(list[0], list[1])
    }
}

parallel (variantMap)
